
# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/lu4p/ToRat_client
    steps:
      - checkout
      - run: go get -u -v github.com/lu4p/ToRat_client
      - run: env GOOS=linux go build -tags "notor"
