
# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /go/src/lu4p
    steps:
      - run: git clone https://github.com/lu4p/ToRat_client.git
      - run: env GOOS=linux go build ./ToRat_client -tags "notor"
